scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  latestVersion:
    name: "Latest cern-sso-cli version"
    kind: githubrelease
    spec:
      owner: "clelange"
      repository: "cern-sso-cli"
      token: "{{ requiredEnv .github.token }}"
      versionfilter:
        kind: semver
        pattern: "*"

  arm64Sha256:
    name: "darwin-arm64-webauthn SHA256"
    kind: shell
    spec:
      command: >-
        curl -sL https://github.com/clelange/cern-sso-cli/releases/download/{{ source `latestVersion` }}/checksums.txt | grep "cern-sso-cli-darwin-arm64-webauthn$" | awk '{print $1}'

  amd64Sha256:
    name: "darwin-amd64-webauthn SHA256"
    kind: shell
    spec:
      command: >-
        curl -sL https://github.com/clelange/cern-sso-cli/releases/download/{{ source `latestVersion` }}/checksums.txt | grep "cern-sso-cli-darwin-amd64-webauthn$" | awk '{print $1}'

targets:
  updateVersion:
    name: "Update version"
    sourceid: latestVersion
    kind: file
    scmid: default
    spec:
      file: Formula/cern-sso-cli.rb
      matchpattern: 'version "[^"]+"'
      replacepattern: 'version "{{ source `latestVersion` }}"'

  updateUrlArm64:
    name: "Update arm64 URL"
    sourceid: latestVersion
    kind: file
    scmid: default
    spec:
      file: Formula/cern-sso-cli.rb
      matchpattern: 'url "https://github.com/clelange/cern-sso-cli/releases/download/v[0-9.]*/cern-sso-cli-darwin-arm64-webauthn"'
      replacepattern: 'url "https://github.com/clelange/cern-sso-cli/releases/download/{{ source `latestVersion` }}/cern-sso-cli-darwin-arm64-webauthn"'

  updateUrlAmd64:
    name: "Update amd64 URL"
    sourceid: latestVersion
    kind: file
    scmid: default
    spec:
      file: Formula/cern-sso-cli.rb
      matchpattern: 'url "https://github.com/clelange/cern-sso-cli/releases/download/v[0-9.]*/cern-sso-cli-darwin-amd64-webauthn"'
      replacepattern: 'url "https://github.com/clelange/cern-sso-cli/releases/download/{{ source `latestVersion` }}/cern-sso-cli-darwin-amd64-webauthn"'

  updateSha256Arm64:
    name: "Update arm64 SHA256"
    sourceid: arm64Sha256
    kind: file
    scmid: default
    spec:
      file: Formula/cern-sso-cli.rb
      matchpattern: 'sha256 "[^"]+"'
      replacepattern: 'sha256 "{{ source `arm64Sha256` }}"'

  updateSha256Amd64:
    name: "Update amd64 SHA256"
    sourceid: amd64Sha256
    kind: file
    scmid: default
    spec:
      file: Formula/cern-sso-cli.rb
      matchpattern: 'sha256 "[^"]+"'
      replacepattern: 'sha256 "{{ source `amd64Sha256` }}"'

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Update cern-sso-cli to "{{ source `latestVersion` }}"
    spec:
      automerge: false
      mergemethod: squash
      sourcebranch: update-cern-sso-cli-{{ source `latestVersion` }}
      description: |
        This automated PR updates cern-sso-cli to version {{ source `latestVersion` }}.
      labels:
        - automation
        - dependencies
