scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  latestVersion:
    name: "Latest cern-sso-cli version"
    kind: githubrelease
    spec:
      owner: "clelange"
      repository: "cern-sso-cli"
      token: "{{ requiredEnv .github.token }}"
      versionfilter:
        kind: semver
        pattern: "*"

  versionNoV:
    name: "Version without v"
    kind: shell
    spec:
      command: 'echo {{ source "latestVersion" }} | sed "s/^v//"'

  amd64Sha:
    name: "AMD64 SHA"
    kind: shell
    spec:
      command: >-
        VERSION={{ source "latestVersion" }} &&
        curl -sL https://github.com/clelange/cern-sso-cli/releases/download/$VERSION/checksums.txt |
        grep "cern-sso-cli-darwin-amd64-webauthn" | awk '{print $1}'

  arm64Sha:
    name: "ARM64 SHA"
    kind: shell
    spec:
      command: >-
        VERSION={{ source "latestVersion" }} &&
        curl -sL https://github.com/clelange/cern-sso-cli/releases/download/$VERSION/checksums.txt |
        grep "cern-sso-cli-darwin-arm64-webauthn" | awk '{print $1}'

targets:
  updateVersion:
    name: "Update formula version"
    sourceid: versionNoV
    kind: file
    scmid: default
    spec:
      file: Formula/cern-sso-cli.rb
      matchpattern: 'version "[^"]*"'
      replacepattern: 'version "{{ source "versionNoV" }}"'

  updateAmd64Url:
    name: "Update AMD64 URL"
    sourceid: latestVersion
    kind: file
    scmid: default
    spec:
      file: Formula/cern-sso-cli.rb
      matchpattern: 'url "https://github.com/clelange/cern-sso-cli/releases/download/v[0-9.]+/cern-sso-cli-darwin-amd64-webauthn"'
      replacepattern: 'url "https://github.com/clelange/cern-sso-cli/releases/download/{{ source "latestVersion" }}/cern-sso-cli-darwin-amd64-webauthn"'

  updateArm64Url:
    name: "Update ARM64 URL"
    sourceid: latestVersion
    kind: file
    scmid: default
    spec:
      file: Formula/cern-sso-cli.rb
      matchpattern: 'url "https://github.com/clelange/cern-sso-cli/releases/download/v[0-9.]+/cern-sso-cli-darwin-arm64-webauthn"'
      replacepattern: 'url "https://github.com/clelange/cern-sso-cli/releases/download/{{ source "latestVersion" }}/cern-sso-cli-darwin-arm64-webauthn"'

  updateAmd64Sha:
    name: "Update AMD64 SHA"
    sourceid: amd64Sha
    kind: file
    scmid: default
    spec:
      file: Formula/cern-sso-cli.rb
      matchpattern: 'sha256 "[^"]*" # darwin-amd64-webauthn'
      replacepattern: 'sha256 "{{ source "amd64Sha" }}" # darwin-amd64-webauthn'

  updateArm64Sha:
    name: "Update ARM64 SHA"
    sourceid: arm64Sha
    kind: file
    scmid: default
    spec:
      file: Formula/cern-sso-cli.rb
      matchpattern: 'sha256 "[^"]*" # darwin-arm64-webauthn'
      replacepattern: 'sha256 "{{ source "arm64Sha" }}" # darwin-arm64-webauthn'

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Update cern-sso-cli to "{{ source "latestVersion" }}"
    spec:
      automerge: false
      mergemethod: squash
      sourcebranch: update-cern-sso-cli-{{ source "latestVersion" }}
      description: |
        This automated PR updates cern-sso-cli to version {{ source "latestVersion" }}.
      labels:
        - automation
        - dependencies
