sources:
  certsInfoFile:
    name: "OSG CA Certificate Information File Content"
    kind: file
    spec:
      file: https://repo.opensciencegrid.org/cadist/ca-certs-version-igtf-new

  certsVersion:
    name: "OSG CA Certificate Version"
    kind: shell
    dependson:
      - certsInfoFile
    spec:
      command: >-
        curl -s https://repo.opensciencegrid.org/cadist/ca-certs-version-igtf-new |
        grep "certsversion=" |
        cut -d= -f2 |
        awk '{print $1}'

  tarballUrl:
    name: "OSG CA Certificate Tarball URL"
    kind: shell
    dependson:
      - certsInfoFile
    spec:
      command: >-
        curl -s https://repo.opensciencegrid.org/cadist/ca-certs-version-igtf-new |
        grep "tarball=" |
        cut -d= -f2

  sha256Sum:
    name: "OSG CA Certificate SHA256 Sum"
    kind: shell
    dependson:
      - certsInfoFile
    spec:
      command: >-
        curl -s https://repo.opensciencegrid.org/cadist/ca-certs-version-igtf-new |
        grep "tarball_sha256sum=" |
        cut -d= -f2

targets:
  updateVersionQuoted:
    name: "Update version with quotes"
    sourceid: certsVersion
    kind: file
    spec:
      file: Formula/osg-ca-certificates.rb
      matchpattern: 'version "(.*)"'
      replacepattern: 'version "{{ source `certsVersion` }}"'

  updateUrl:
    name: "Update tarball URL"
    sourceid: tarballUrl
    kind: file
    spec:
      file: Formula/osg-ca-certificates.rb
      matchpattern: 'url "[^"]+"'
      replacepattern: 'url "{{ source `tarballUrl` }}"'

  updateSha:
    name: "Update SHA256 checksum"
    sourceid: sha256Sum
    kind: file
    spec:
      file: Formula/osg-ca-certificates.rb
      matchpattern: 'sha256 "[^"]+"'
      replacepattern: 'sha256 "{{ source `sha256Sum` }}"'

actions:
  default:
    kind: github/pullrequest
    scmid: default
    spec:
      automerge: false
      mergemethod: squash
      title: "Update OSG CA Certificates to {{ source `certsVersion` }}"
      description: |
        This automated PR updates the OSG CA Certificates to version {{ source `certsVersion` }}.

        * New version: {{ source `certsVersion` }}
        * Tarball URL: {{ source `tarballUrl` }}
        * SHA256: {{ source `sha256Sum` }}
      labels:
        - automation
        - dependencies
