scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  certsVersion:
    name: "OSG CA Certificate Version"
    kind: shell
    spec:
      command: >-
        curl -s https://repo.opensciencegrid.org/cadist/ca-certs-version-igtf-new |
        grep "certsversion=" |
        cut -d= -f2 |
        awk '{print $1}'

  tarballUrl:
    name: "OSG CA Certificate Tarball URL"
    kind: shell
    spec:
      command: >-
        curl -s https://repo.opensciencegrid.org/cadist/ca-certs-version-igtf-new |
        grep "tarball=" |
        cut -d= -f2

  sha256Sum:
    name: "OSG CA Certificate SHA256 Sum"
    kind: shell
    spec:
      command: >-
        curl -s https://repo.opensciencegrid.org/cadist/ca-certs-version-igtf-new |
        grep "tarball_sha256sum=" |
        cut -d= -f2

  validateContent:
    name: "Validate CA Certificates content"
    kind: shell
    spec:
      command: >-
        tempfile=$(mktemp) &&
        curl -sfL --max-time 30 "{{ source `tarballUrl` }}" -o "$tempfile" &&
        echo "{{ source `sha256Sum` }} $tempfile" | sha256sum -c -

targets:
  updateUrl:
    name: "Update tarball URL"
    sourceid: tarballUrl
    kind: file
    spec:
      file: Formula/osg-ca-certificates.rb
      matchpattern: 'url "[^"]+"'
      replacepattern: 'url "{{ source `tarballUrl` }}"'

  updateSha:
    name: "Update SHA256 checksum"
    sourceid: sha256Sum
    kind: file
    spec:
      file: Formula/osg-ca-certificates.rb
      matchpattern: 'sha256 "[^"]+"'
      replacepattern: 'sha256 "{{ source `sha256Sum` }}"'

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Update OSG CA Certificates to "{{ source `certsVersion` }}"
    spec:
      automerge: false
      mergemethod: squash
      description: |
        This automated PR updates the OSG CA Certificates to version {{ source `certsVersion` }}.

        * New version: {{ source `certsVersion` }}
        * Tarball URL: {{ source `tarballUrl` }}
        * SHA256: {{ source `sha256Sum` }}
      labels:
        - automation
        - dependencies
