scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  latestVersion:
    name: "Latest cern-sso-cli version"
    kind: githubrelease
    spec:
      owner: "clelange"
      repository: "cern-sso-cli"
      token: "{{ requiredEnv .github.token }}"
      versionfilter:
        kind: semver
        pattern: "*"

  versionNoV:
    name: "Version without v"
    kind: shell
    spec:
      command: 'echo {{ source "latestVersion" }} | sed "s/^v//"'

  amd64Sha:
    name: "AMD64 SHA"
    kind: shell
    spec:
      command: >-
        VERSION={{ source "latestVersion" }} &&
        curl -sL https://github.com/clelange/cern-sso-cli/releases/download/$VERSION/checksums.txt |
        grep "cern-sso-cli-darwin-amd64-webauthn" | awk '{print $1}'

  arm64Sha:
    name: "ARM64 SHA"
    kind: shell
    spec:
      command: >-
        VERSION={{ source "latestVersion" }} &&
        curl -sL https://github.com/clelange/cern-sso-cli/releases/download/$VERSION/checksums.txt |
        grep "cern-sso-cli-darwin-arm64-webauthn" | awk '{print $1}'

targets:
  updateFormula:
    name: Update cern-sso-cli to {{ source "latestVersion" }}
    kind: file
    sourceid: latestVersion
    scmid: default
    spec:
      file: Formula/cern-sso-cli.rb
      content: |
        class CernSsoCli < Formula
          desc "Command-line interface to obtain CERN SSO cookies and tokens"
          homepage "https://github.com/clelange/cern-sso-cli"
          version "{{ source "versionNoV" }}"
          license "GPL-3.0-only"

          on_macos do
            if Hardware::CPU.intel?
              url "https://github.com/clelange/cern-sso-cli/releases/download/{{ source "latestVersion" }}/cern-sso-cli-darwin-amd64-webauthn"
              sha256 "{{ source "amd64Sha" }}" # darwin-amd64-webauthn
            elsif Hardware::CPU.arm?
              url "https://github.com/clelange/cern-sso-cli/releases/download/{{ source "latestVersion" }}/cern-sso-cli-darwin-arm64-webauthn"
              sha256 "{{ source "arm64Sha" }}" # darwin-arm64-webauthn
            end
          end

          depends_on "libfido2"

          def install
            bin.install "cern-sso-cli-darwin-amd64-webauthn" => "cern-sso-cli" if Hardware::CPU.intel?
            bin.install "cern-sso-cli-darwin-arm64-webauthn" => "cern-sso-cli" if Hardware::CPU.arm?

            chmod 0755, bin/"cern-sso-cli"
            generate_completions_from_executable(bin/"cern-sso-cli", "completion")
          end



          test do
            system bin/"cern-sso-cli", "--version"
          end
        end

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Update cern-sso-cli to "{{ source "latestVersion" }}"
    spec:
      automerge: false
      mergemethod: squash
      sourcebranch: update-cern-sso-cli-{{ source "latestVersion" }}
      description: |
        This automated PR updates cern-sso-cli to version {{ source "latestVersion" }}.
      labels:
        - automation
        - dependencies
