scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  latestVersion:
    name: "Latest cern-sso-cli version"
    kind: githubrelease
    spec:
      owner: "clelange"
      repository: "cern-sso-cli"
      token: "{{ requiredEnv .github.token }}"
      versionfilter:
        kind: semver
        pattern: "*"

targets:
  updateAll:
    name: "Update all version and checksums"
    sourceid: latestVersion
    kind: shell
    scmid: default
    spec:
      command: >-
        VERSION={{ source `latestVersion` }} &&
        VERSION_NO_V=$(echo $VERSION | sed 's/^v//') &&
        curl -sL https://github.com/clelange/cern-sso-cli/releases/download/$VERSION/checksums.txt > checksums.txt &&
        AMD64_SHA=$(grep "cern-sso-cli-darwin-amd64-webauthn$" checksums.txt | awk '{print $1}') &&
        ARM64_SHA=$(grep "cern-sso-cli-darwin-arm64-webauthn$" checksums.txt | awk '{print $1}') &&
        rm -f checksums.txt &&
        sed -i.bak "s|version \"[^\"]*\"|version \"$VERSION_NO_V\"|g" Formula/cern-sso-cli.rb &&
        sed -i.bak "s|https://github.com/clelange/cern-sso-cli/releases/download/v[0-9.]*/cern-sso-cli-darwin-arm64-webauthn|https://github.com/clelange/cern-sso-cli/releases/download/$VERSION/cern-sso-cli-darwin-arm64-webauthn|g" Formula/cern-sso-cli.rb &&
        sed -i.bak "s|https://github.com/clelange/cern-sso-cli/releases/download/v[0-9.]*/cern-sso-cli-darwin-amd64-webauthn|https://github.com/clelange/cern-sso-cli/releases/download/$VERSION/cern-sso-cli-darwin-amd64-webauthn|g" Formula/cern-sso-cli.rb &&
        sed -i.bak "s|sha256 \".*\" # darwin-arm64-webauthn|sha256 \"$ARM64_SHA\" # darwin-arm64-webauthn|g" Formula/cern-sso-cli.rb &&
        sed -i.bak "s|sha256 \".*\" # darwin-amd64-webauthn|sha256 \"$AMD64_SHA\" # darwin-amd64-webauthn|g" Formula/cern-sso-cli.rb &&
        rm -f Formula/cern-sso-cli.rb.bak

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Update cern-sso-cli to "{{ source `latestVersion` }}"
    spec:
      automerge: false
      mergemethod: squash
      sourcebranch: update-cern-sso-cli-{{ source `latestVersion` }}
      description: |
        This automated PR updates cern-sso-cli to version {{ source `latestVersion` }}.
      labels:
        - automation
        - dependencies
